# Generated by Django 3.1.7 on 2021-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0002_auto_20210222_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(help_text='Выберите доступные Обьемы продукта', to='len_parfume.Size', verbose_name='размеры'),
        ),
    ]
