# Generated by Django 3.1.7 on 2021-02-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0004_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название бренда'),
        ),
    ]
