# Generated by Django 3.1.7 on 2021-03-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0007_auto_20210302_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='whishlist',
            name='whishlist',
            field=models.BooleanField(default=False, verbose_name='В избраном'),
        ),
    ]
